name: adapt-cluster-id
run-name: Adapt RHDH Cluster ID in templates
on:
  workflow_dispatch:
    inputs:
      cluster_id:
        description: 'Your personal RHDH Cluster ID'
        required: true
        type: string
        default: 'XXX_XXX_XXX'
jobs:
  adapt-cluster-id:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: adapt cluster id
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "<XXX_XXX_XXX>"
          replace: ${{ inputs.cluster_id }}
          include: "**template.yaml"
          regex: false
      - name: commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
